#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "${0%/*}" && pwd)"

"$ROOT_DIR/SplitAndRecombineHydro/Allrun"
"$ROOT_DIR/SplitAndRecombineMixing/Allrun"

touch "$ROOT_DIR/SplitAndRecombineHydro/SplitAndRecombineHydro.foam"
touch "$ROOT_DIR/SplitAndRecombineMixing/SplitAndRecombineMixing.foam"

echo "=== Done ==="
